// Search Results
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS'
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const RECEIVE_CATALOGS = 'RECEIVE_CATALOGS'
export const RECEIVE_TEXTS = 'RECEIVE_TEXTS'
export const ERROR_SEARCH_RESULTS = 'ERROR_SEARCH_RESULTS'

// Term History
export const ADD_TERM_TO_HISTORY = 'ADD_TERM_TO_HISTORY'

// Search Type Display
export const SET_SEARCH_TYPE_DISPLAY = 'SET_SEARCH_TYPE_DISPLAY'

// Offsets
export const SET_OFFSETS = 'SET_OFFSETS'
export const RESET_OFFSETS = 'RESET_OFFSETS'

// Favorites
export const ADD_RESULT_TO_FAVORITES = 'ADD_RESULT_TO_FAVORITES'
export const DELETE_RESULT_FROM_FAVORITES = 'DELETE_RESULT_FROM_FAVORITES'
