export const statics = {
    menuItems: ['catalogs', 'texts'],
    fullTextItem: 'Full Text',
    catalogs_keys: ['priauthtib', 'ttltib'],
    texts_keys: ['authortib', 'titletib'],
    searchOptions: {
        searchOffset: 0,
        resultSetSize: 10,
    },
    searchTerms: [
        `STONG TSUL THA`,
        `MDZES PA DBYIG GNYEN`,
        `GUHYASAMAJA`,
        `DPAL 'KHOR LO BDE MCHOG`,
        `RGYAS PAR MDZAD PA`,
        `SHIS MKHAS GRUB KYIS BSKUL BA LTAR`,
        `MI JOGS`,
        `NOTES ON THE ART OF INTERPRETATION`,
        `SHANTIDEVA`,
        `PA'ANG T'A RA N'A`,
        `NAGARJUNA`,
        `BLO BZANG GRAGS PA`,
        `RJE TZONG KHA PA`,
    ],
}
