export const statics = {
    menuItems: ['catalogs', 'texts'],
    fullTextItem: 'Full Text',
    hlt_catalogs_keys: ['priauthtib', 'ttltib'],
    hlt_texts_keys: ['authortib', 'titletib'],
    meta_keys: [
        'pagenumbers',
        'sizepages',
        'sizeprtarea',
        'volume',
        'catalognumber',
        'collection',
    ],
    author_keys: [
        'authoreng',
        'authorskt',
        'priautheng',
        'priauthtib',
        'authortib',
        'authordates',
    ],
    title_keys: [
        'titleeng',
        'titletib',
        'titleskt',
        'ttleng',
        'ttltibbrf',
        'ttltib',
        'ttlskt',
    ],
    searchOptions: {
        searchOffset: 0,
        resultSetSize: 10,
    },
    searchTerms: [
        `STONG TSUL THA`,
        `MDZES PA DBYIG GNYEN`,
        `GUHYASAMAJA`,
        `DPAL 'KHOR LO BDE MCHOG`,
        `RGYAS PAR MDZAD PA`,
        `SHIS MKHAS GRUB KYIS BSKUL BA LTAR`,
        `MI JOGS`,
        `NOTES ON THE ART OF INTERPRETATION`,
        `SHANTIDEVA`,
        `PA'ANG T'A RA N'A`,
        `NAGARJUNA`,
        `BLO BZANG GRAGS PA`,
        `RJE TZONG KHA PA`,
    ],
}
